# Generated by Django 5.0.3 on 2024-03-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("description", models.TextField()),
            ],
        ),
    ]
