# Generated by Django 4.2.11 on 2024-03-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address_from",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="address_to",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
