# Generated by Django 4.2.11 on 2024-03-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_order_address_from_order_address_to"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                ("name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                ("description", models.TextField()),
            ],
        ),
    ]
